// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgljohyumbsparctxdxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnbGpvaHl1bWJzcGFyY3R4ZHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzQwNjksImV4cCI6MjA2Mzc1MDA2OX0.PU1MUg2CArcwR2fv2YGnrRhaWzZJ2sBrcGalP5c9A8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);